### ISSUE TITLE
error after update to 0.2.1

### ISSUE THREAD

**Issue by lpt2007** [txitxo0/congatudo-add-on#21]
I have an error after upate to 0.2.1

```
[17:40:09] INFO: Using configuration from '/config/valetudo.json'...
[2021-10-16T15:40:12.451Z] [INFO] Loading configuration file: /config/valetudo.json
[2021-10-16T15:40:12.811Z] [INFO] Set Logfile to /tmp/valetudo.log
[2021-10-16T15:40:12.818Z] [ERROR] Error while initializing robot implementation. Shutting down  Error: Couldn't find a suitable ValetudoRobot implementation.
    at Function.autodetectRobotImplementation (/snapshot/app/backend/lib/core/ValetudoRobotFactory.js:53:19)
    at Function.getRobotImplementation (/snapshot/app/backend/lib/core/ValetudoRobotFactory.js:17:45)
    at new Valetudo (/snapshot/app/backend/lib/Valetudo.js:32:62)
    at Object.<anonymous> (/snapshot/app/backend/index.js:6:16)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Module._compile (pkg/prelude/bootstrap.js:1758:32)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.runMain (pkg/prelude/bootstrap.js:1804:12)
    at node:internal/main/run_main_module:17:47
[cmd] dumb-init exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
```

**Comment by txitxo0** [comment]
Due inactivity, issue closed
